# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Starting maildev
        run: make install start
      - uses: iFaxity/wait-on-action@v1
        with:
          resource: http://127.0.0.1:1080
      - name: Curl Maildev2 
        run: curl http://127.0.0.1:1080/#/
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          wait-on: "http://localhost:1080"
          wait-on-timeout: 120
          build: make install build
          start: make test
